[package]
name = "Get_Softwares"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_System_Com",
] }
winreg = "0.52"
glob = "0.3"
serde = { version = "1", features = ["derive"] }